/*
  # Add Slug Column to Services Table (Version 2)

  1. Changes
    - Add `slug` column to services table for URL-friendly identifiers
    - Generate unique slugs for all existing services based on their Russian names
    - If duplicates exist, append a number to make them unique
    - Create unique index on slug column to prevent duplicates

  2. Notes
    - Slugs are generated by transliterating Russian names and converting to lowercase
    - Spaces and special characters are replaced with hyphens
    - Duplicate slugs are handled by appending sequential numbers
*/

-- Add slug column to services table
ALTER TABLE services ADD COLUMN IF NOT EXISTS slug TEXT;

-- Create function to generate slug from Russian text
CREATE OR REPLACE FUNCTION generate_slug(text_ru TEXT) RETURNS TEXT AS $$
DECLARE
  slug TEXT;
  transliterated TEXT;
BEGIN
  -- Simple transliteration map for common Russian characters
  transliterated := text_ru;
  transliterated := REPLACE(transliterated, 'а', 'a');
  transliterated := REPLACE(transliterated, 'б', 'b');
  transliterated := REPLACE(transliterated, 'в', 'v');
  transliterated := REPLACE(transliterated, 'г', 'g');
  transliterated := REPLACE(transliterated, 'д', 'd');
  transliterated := REPLACE(transliterated, 'е', 'e');
  transliterated := REPLACE(transliterated, 'ё', 'yo');
  transliterated := REPLACE(transliterated, 'ж', 'zh');
  transliterated := REPLACE(transliterated, 'з', 'z');
  transliterated := REPLACE(transliterated, 'и', 'i');
  transliterated := REPLACE(transliterated, 'й', 'y');
  transliterated := REPLACE(transliterated, 'к', 'k');
  transliterated := REPLACE(transliterated, 'л', 'l');
  transliterated := REPLACE(transliterated, 'м', 'm');
  transliterated := REPLACE(transliterated, 'н', 'n');
  transliterated := REPLACE(transliterated, 'о', 'o');
  transliterated := REPLACE(transliterated, 'п', 'p');
  transliterated := REPLACE(transliterated, 'р', 'r');
  transliterated := REPLACE(transliterated, 'с', 's');
  transliterated := REPLACE(transliterated, 'т', 't');
  transliterated := REPLACE(transliterated, 'у', 'u');
  transliterated := REPLACE(transliterated, 'ф', 'f');
  transliterated := REPLACE(transliterated, 'х', 'h');
  transliterated := REPLACE(transliterated, 'ц', 'ts');
  transliterated := REPLACE(transliterated, 'ч', 'ch');
  transliterated := REPLACE(transliterated, 'ш', 'sh');
  transliterated := REPLACE(transliterated, 'щ', 'sch');
  transliterated := REPLACE(transliterated, 'ъ', '');
  transliterated := REPLACE(transliterated, 'ы', 'y');
  transliterated := REPLACE(transliterated, 'ь', '');
  transliterated := REPLACE(transliterated, 'э', 'e');
  transliterated := REPLACE(transliterated, 'ю', 'yu');
  transliterated := REPLACE(transliterated, 'я', 'ya');
  
  -- Convert to lowercase and replace spaces/special chars with hyphens
  slug := LOWER(transliterated);
  slug := REGEXP_REPLACE(slug, '[^a-z0-9]+', '-', 'g');
  slug := TRIM(BOTH '-' FROM slug);
  
  RETURN slug;
END;
$$ LANGUAGE plpgsql;

-- Generate unique slugs for all existing services
DO $$
DECLARE
  service_record RECORD;
  base_slug TEXT;
  final_slug TEXT;
  counter INTEGER;
BEGIN
  FOR service_record IN SELECT id, name_ru FROM services WHERE slug IS NULL ORDER BY sort_order
  LOOP
    base_slug := generate_slug(service_record.name_ru);
    final_slug := base_slug;
    counter := 1;
    
    -- Check if slug already exists, append number if needed
    WHILE EXISTS (SELECT 1 FROM services WHERE slug = final_slug AND id != service_record.id) LOOP
      final_slug := base_slug || '-' || counter;
      counter := counter + 1;
    END LOOP;
    
    UPDATE services SET slug = final_slug WHERE id = service_record.id;
  END LOOP;
END $$;

-- Make slug NOT NULL after populating
ALTER TABLE services ALTER COLUMN slug SET NOT NULL;

-- Create unique index on slug
CREATE UNIQUE INDEX IF NOT EXISTS services_slug_unique ON services(slug);